/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CommentWithFiles', function() {
      beforeEach(function() {
        instance = new FreeloApi.CommentWithFiles();
      });

      it('should create an instance of CommentWithFiles', function() {
        // TODO: update the code to test CommentWithFiles
        expect(instance).to.be.a(FreeloApi.CommentWithFiles);
      });

      it('should have the property author (base name: "author")', function() {
        // TODO: update the code to test the property author
        expect(instance).to.have.property('author');
        // expect(instance.author).to.be(expectedValueLiteral);
      });

      it('should have the property isDescription (base name: "is_description")', function() {
        // TODO: update the code to test the property isDescription
        expect(instance).to.have.property('isDescription');
        // expect(instance.isDescription).to.be(expectedValueLiteral);
      });

      it('should have the property commentsReactions (base name: "comments_reactions")', function() {
        // TODO: update the code to test the property commentsReactions
        expect(instance).to.have.property('commentsReactions');
        // expect(instance.commentsReactions).to.be(expectedValueLiteral);
      });

      it('should have the property files (base name: "files")', function() {
        // TODO: update the code to test the property files
        expect(instance).to.have.property('files');
        // expect(instance.files).to.be(expectedValueLiteral);
      });

    });
  });

}));
