/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreatefromtemplateTemplateIdBody', function() {
      beforeEach(function() {
        instance = new FreeloApi.CreatefromtemplateTemplateIdBody();
      });

      it('should create an instance of CreatefromtemplateTemplateIdBody', function() {
        // TODO: update the code to test CreatefromtemplateTemplateIdBody
        expect(instance).to.be.a(FreeloApi.CreatefromtemplateTemplateIdBody);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property projectOwnerId (base name: "project_owner_id")', function() {
        // TODO: update the code to test the property projectOwnerId
        expect(instance).to.have.property('projectOwnerId');
        // expect(instance.projectOwnerId).to.be(expectedValueLiteral);
      });

      it('should have the property currencyIso (base name: "currency_iso")', function() {
        // TODO: update the code to test the property currencyIso
        expect(instance).to.have.property('currencyIso');
        // expect(instance.currencyIso).to.be(expectedValueLiteral);
      });

      it('should have the property presetDateFrom (base name: "preset_date_from")', function() {
        // TODO: update the code to test the property presetDateFrom
        expect(instance).to.have.property('presetDateFrom');
        // expect(instance.presetDateFrom).to.be(expectedValueLiteral);
      });

      it('should have the property generalSettings (base name: "general_settings")', function() {
        // TODO: update the code to test the property generalSettings
        expect(instance).to.have.property('generalSettings');
        // expect(instance.generalSettings).to.be(expectedValueLiteral);
      });

      it('should have the property usersIds (base name: "users_ids")', function() {
        // TODO: update the code to test the property usersIds
        expect(instance).to.have.property('usersIds');
        // expect(instance.usersIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
