/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreatefromtemplateTemplateIdBody1', function() {
      beforeEach(function() {
        instance = new FreeloApi.CreatefromtemplateTemplateIdBody1();
      });

      it('should create an instance of CreatefromtemplateTemplateIdBody1', function() {
        // TODO: update the code to test CreatefromtemplateTemplateIdBody1
        expect(instance).to.be.a(FreeloApi.CreatefromtemplateTemplateIdBody1);
      });

      it('should have the property tasklistId (base name: "tasklist_id")', function() {
        // TODO: update the code to test the property tasklistId
        expect(instance).to.have.property('tasklistId');
        // expect(instance.tasklistId).to.be(expectedValueLiteral);
      });

      it('should have the property targetProjectId (base name: "target_project_id")', function() {
        // TODO: update the code to test the property targetProjectId
        expect(instance).to.have.property('targetProjectId');
        // expect(instance.targetProjectId).to.be(expectedValueLiteral);
      });

      it('should have the property targetTasklistId (base name: "target_tasklist_id")', function() {
        // TODO: update the code to test the property targetTasklistId
        expect(instance).to.have.property('targetTasklistId');
        // expect(instance.targetTasklistId).to.be(expectedValueLiteral);
      });

      it('should have the property presetDateFrom (base name: "preset_date_from")', function() {
        // TODO: update the code to test the property presetDateFrom
        expect(instance).to.have.property('presetDateFrom');
        // expect(instance.presetDateFrom).to.be(expectedValueLiteral);
      });

      it('should have the property usersIds (base name: "users_ids")', function() {
        // TODO: update the code to test the property usersIds
        expect(instance).to.have.property('usersIds');
        // expect(instance.usersIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
