/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CustomFieldWithValue', function() {
      beforeEach(function() {
        instance = new FreeloApi.CustomFieldWithValue();
      });

      it('should create an instance of CustomFieldWithValue', function() {
        // TODO: update the code to test CustomFieldWithValue
        expect(instance).to.be.a(FreeloApi.CustomFieldWithValue);
      });

      it('should have the property fieldUuid (base name: "field_uuid")', function() {
        // TODO: update the code to test the property fieldUuid
        expect(instance).to.have.property('fieldUuid');
        // expect(instance.fieldUuid).to.be(expectedValueLiteral);
      });

      it('should have the property customFieldsTypesUuid (base name: "custom_fields_types_uuid")', function() {
        // TODO: update the code to test the property customFieldsTypesUuid
        expect(instance).to.have.property('customFieldsTypesUuid');
        // expect(instance.customFieldsTypesUuid).to.be(expectedValueLiteral);
      });

      it('should have the property projectId (base name: "project_id")', function() {
        // TODO: update the code to test the property projectId
        expect(instance).to.have.property('projectId');
        // expect(instance.projectId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property priority (base name: "priority")', function() {
        // TODO: update the code to test the property priority
        expect(instance).to.have.property('priority');
        // expect(instance.priority).to.be(expectedValueLiteral);
      });

      it('should have the property fieldDateAdd (base name: "field_date_add")', function() {
        // TODO: update the code to test the property fieldDateAdd
        expect(instance).to.have.property('fieldDateAdd');
        // expect(instance.fieldDateAdd).to.be(expectedValueLiteral);
      });

      it('should have the property valueUuid (base name: "value_uuid")', function() {
        // TODO: update the code to test the property valueUuid
        expect(instance).to.have.property('valueUuid');
        // expect(instance.valueUuid).to.be(expectedValueLiteral);
      });

      it('should have the property valueAuthorId (base name: "value_author_id")', function() {
        // TODO: update the code to test the property valueAuthorId
        expect(instance).to.have.property('valueAuthorId');
        // expect(instance.valueAuthorId).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property valueDateAdd (base name: "value_date_add")', function() {
        // TODO: update the code to test the property valueDateAdd
        expect(instance).to.have.property('valueDateAdd');
        // expect(instance.valueDateAdd).to.be(expectedValueLiteral);
      });

      it('should have the property valueDateEditedAt (base name: "value_date_edited_at")', function() {
        // TODO: update the code to test the property valueDateEditedAt
        expect(instance).to.have.property('valueDateEditedAt');
        // expect(instance.valueDateEditedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
