/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CustomFieldEnumValue', function() {
      beforeEach(function() {
        instance = new FreeloApi.CustomFieldEnumValue();
      });

      it('should create an instance of CustomFieldEnumValue', function() {
        // TODO: update the code to test CustomFieldEnumValue
        expect(instance).to.be.a(FreeloApi.CustomFieldEnumValue);
      });

      it('should have the property uuid (base name: "uuid")', function() {
        // TODO: update the code to test the property uuid
        expect(instance).to.have.property('uuid');
        // expect(instance.uuid).to.be(expectedValueLiteral);
      });

      it('should have the property taskId (base name: "task_id")', function() {
        // TODO: update the code to test the property taskId
        expect(instance).to.have.property('taskId');
        // expect(instance.taskId).to.be(expectedValueLiteral);
      });

      it('should have the property customFieldUuid (base name: "custom_field_uuid")', function() {
        // TODO: update the code to test the property customFieldUuid
        expect(instance).to.have.property('customFieldUuid');
        // expect(instance.customFieldUuid).to.be(expectedValueLiteral);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property dateAdd (base name: "date_add")', function() {
        // TODO: update the code to test the property dateAdd
        expect(instance).to.have.property('dateAdd');
        // expect(instance.dateAdd).to.be(expectedValueLiteral);
      });

      it('should have the property dateEditedAt (base name: "date_edited_at")', function() {
        // TODO: update the code to test the property dateEditedAt
        expect(instance).to.have.property('dateEditedAt');
        // expect(instance.dateEditedAt).to.be(expectedValueLiteral);
      });

      it('should have the property authorId (base name: "author_id")', function() {
        // TODO: update the code to test the property authorId
        expect(instance).to.have.property('authorId');
        // expect(instance.authorId).to.be(expectedValueLiteral);
      });

    });
  });

}));
