/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SearchBody', function() {
      beforeEach(function() {
        instance = new FreeloApi.SearchBody();
      });

      it('should create an instance of SearchBody', function() {
        // TODO: update the code to test SearchBody
        expect(instance).to.be.a(FreeloApi.SearchBody);
      });

      it('should have the property searchQuery (base name: "search_query")', function() {
        // TODO: update the code to test the property searchQuery
        expect(instance).to.have.property('searchQuery');
        // expect(instance.searchQuery).to.be(expectedValueLiteral);
      });

      it('should have the property projectsIds (base name: "projects_ids")', function() {
        // TODO: update the code to test the property projectsIds
        expect(instance).to.have.property('projectsIds');
        // expect(instance.projectsIds).to.be(expectedValueLiteral);
      });

      it('should have the property tasklistsIds (base name: "tasklists_ids")', function() {
        // TODO: update the code to test the property tasklistsIds
        expect(instance).to.have.property('tasklistsIds');
        // expect(instance.tasklistsIds).to.be(expectedValueLiteral);
      });

      it('should have the property tasksIds (base name: "tasks_ids")', function() {
        // TODO: update the code to test the property tasksIds
        expect(instance).to.have.property('tasksIds');
        // expect(instance.tasksIds).to.be(expectedValueLiteral);
      });

      it('should have the property authorsIds (base name: "authors_ids")', function() {
        // TODO: update the code to test the property authorsIds
        expect(instance).to.have.property('authorsIds');
        // expect(instance.authorsIds).to.be(expectedValueLiteral);
      });

      it('should have the property workersIds (base name: "workers_ids")', function() {
        // TODO: update the code to test the property workersIds
        expect(instance).to.have.property('workersIds');
        // expect(instance.workersIds).to.be(expectedValueLiteral);
      });

      it('should have the property stateIds (base name: "state_ids")', function() {
        // TODO: update the code to test the property stateIds
        expect(instance).to.have.property('stateIds');
        // expect(instance.stateIds).to.be(expectedValueLiteral);
      });

      it('should have the property lang (base name: "lang")', function() {
        // TODO: update the code to test the property lang
        expect(instance).to.have.property('lang');
        // expect(instance.lang).to.be(expectedValueLiteral);
      });

      it('should have the property dueDate (base name: "due_date")', function() {
        // TODO: update the code to test the property dueDate
        expect(instance).to.have.property('dueDate');
        // expect(instance.dueDate).to.be(expectedValueLiteral);
      });

      it('should have the property entityType (base name: "entity_type")', function() {
        // TODO: update the code to test the property entityType
        expect(instance).to.have.property('entityType');
        // expect(instance.entityType).to.be(expectedValueLiteral);
      });

      it('should have the property page (base name: "page")', function() {
        // TODO: update the code to test the property page
        expect(instance).to.have.property('page');
        // expect(instance.page).to.be(expectedValueLiteral);
      });

      it('should have the property limit (base name: "limit")', function() {
        // TODO: update the code to test the property limit
        expect(instance).to.have.property('limit');
        // expect(instance.limit).to.be(expectedValueLiteral);
      });

    });
  });

}));
