/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TaskSummary', function() {
      beforeEach(function() {
        instance = new FreeloApi.TaskSummary();
      });

      it('should create an instance of TaskSummary', function() {
        // TODO: update the code to test TaskSummary
        expect(instance).to.be.a(FreeloApi.TaskSummary);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property dateAdd (base name: "date_add")', function() {
        // TODO: update the code to test the property dateAdd
        expect(instance).to.have.property('dateAdd');
        // expect(instance.dateAdd).to.be(expectedValueLiteral);
      });

      it('should have the property dateEditedAt (base name: "date_edited_at")', function() {
        // TODO: update the code to test the property dateEditedAt
        expect(instance).to.have.property('dateEditedAt');
        // expect(instance.dateEditedAt).to.be(expectedValueLiteral);
      });

      it('should have the property dueDate (base name: "due_date")', function() {
        // TODO: update the code to test the property dueDate
        expect(instance).to.have.property('dueDate');
        // expect(instance.dueDate).to.be(expectedValueLiteral);
      });

      it('should have the property dueDateEnd (base name: "due_date_end")', function() {
        // TODO: update the code to test the property dueDateEnd
        expect(instance).to.have.property('dueDateEnd');
        // expect(instance.dueDateEnd).to.be(expectedValueLiteral);
      });

      it('should have the property countComments (base name: "count_comments")', function() {
        // TODO: update the code to test the property countComments
        expect(instance).to.have.property('countComments');
        // expect(instance.countComments).to.be(expectedValueLiteral);
      });

      it('should have the property countSubtasks (base name: "count_subtasks")', function() {
        // TODO: update the code to test the property countSubtasks
        expect(instance).to.have.property('countSubtasks');
        // expect(instance.countSubtasks).to.be(expectedValueLiteral);
      });

      it('should have the property author (base name: "author")', function() {
        // TODO: update the code to test the property author
        expect(instance).to.have.property('author');
        // expect(instance.author).to.be(expectedValueLiteral);
      });

      it('should have the property worker (base name: "worker")', function() {
        // TODO: update the code to test the property worker
        expect(instance).to.have.property('worker');
        // expect(instance.worker).to.be(expectedValueLiteral);
      });

      it('should have the property labels (base name: "labels")', function() {
        // TODO: update the code to test the property labels
        expect(instance).to.have.property('labels');
        // expect(instance.labels).to.be(expectedValueLiteral);
      });

      it('should have the property parentTaskId (base name: "parent_task_id")', function() {
        // TODO: update the code to test the property parentTaskId
        expect(instance).to.have.property('parentTaskId');
        // expect(instance.parentTaskId).to.be(expectedValueLiteral);
      });

      it('should have the property totalTimeEstimate (base name: "total_time_estimate")', function() {
        // TODO: update the code to test the property totalTimeEstimate
        expect(instance).to.have.property('totalTimeEstimate');
        // expect(instance.totalTimeEstimate).to.be(expectedValueLiteral);
      });

      it('should have the property usersTimeEstimates (base name: "users_time_estimates")', function() {
        // TODO: update the code to test the property usersTimeEstimates
        expect(instance).to.have.property('usersTimeEstimates');
        // expect(instance.usersTimeEstimates).to.be(expectedValueLiteral);
      });

    });
  });

}));
