/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeloApi.CustomFieldsApi();
  });

  describe('(package)', function() {
    describe('CustomFieldsApi', function() {
      describe('addOrEditCustomFieldValue', function() {
        it('should call addOrEditCustomFieldValue successfully', function(done) {
          // TODO: uncomment, update parameter values for addOrEditCustomFieldValue call and complete the assertions
          /*

          instance.addOrEditCustomFieldValue(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20028);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addOrEditEnumValue', function() {
        it('should call addOrEditEnumValue successfully', function(done) {
          // TODO: uncomment, update parameter values for addOrEditEnumValue call and complete the assertions
          /*

          instance.addOrEditEnumValue(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20029);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createCustomField', function() {
        it('should call createCustomField successfully', function(done) {
          // TODO: uncomment, update parameter values for createCustomField call and complete the assertions
          /*

          instance.createCustomField(body, projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20027);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createEnumOption', function() {
        it('should call createEnumOption successfully', function(done) {
          // TODO: uncomment, update parameter values for createEnumOption call and complete the assertions
          /*

          instance.createEnumOption(body, customFieldUuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20031);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCustomField', function() {
        it('should call deleteCustomField successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCustomField call and complete the assertions
          /*

          instance.deleteCustomField(uuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCustomFieldValue', function() {
        it('should call deleteCustomFieldValue successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCustomFieldValue call and complete the assertions
          /*

          instance.deleteCustomFieldValue(uuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteEnumOption', function() {
        it('should call deleteEnumOption successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteEnumOption call and complete the assertions
          /*

          instance.deleteEnumOption(customFieldEnumUuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editEnumOption', function() {
        it('should call editEnumOption successfully', function(done) {
          // TODO: uncomment, update parameter values for editEnumOption call and complete the assertions
          /*

          instance.editEnumOption(body, customFieldEnumUuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20031);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findCustomFieldsByProject', function() {
        it('should call findCustomFieldsByProject successfully', function(done) {
          // TODO: uncomment, update parameter values for findCustomFieldsByProject call and complete the assertions
          /*

          instance.findCustomFieldsByProject(projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20032);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('forceDeleteEnumOption', function() {
        it('should call forceDeleteEnumOption successfully', function(done) {
          // TODO: uncomment, update parameter values for forceDeleteEnumOption call and complete the assertions
          /*

          instance.forceDeleteEnumOption(customFieldEnumUuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCustomFieldTypes', function() {
        it('should call getCustomFieldTypes successfully', function(done) {
          // TODO: uncomment getCustomFieldTypes call and complete the assertions
          /*

          instance.getCustomFieldTypes(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20026);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getEnumOptionsForCustomField', function() {
        it('should call getEnumOptionsForCustomField successfully', function(done) {
          // TODO: uncomment, update parameter values for getEnumOptionsForCustomField call and complete the assertions
          /*

          instance.getEnumOptionsForCustomField(customFieldUuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20030);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('renameCustomField', function() {
        it('should call renameCustomField successfully', function(done) {
          // TODO: uncomment, update parameter values for renameCustomField call and complete the assertions
          /*

          instance.renameCustomField(body, uuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20027);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('restoreCustomField', function() {
        it('should call restoreCustomField successfully', function(done) {
          // TODO: uncomment, update parameter values for restoreCustomField call and complete the assertions
          /*

          instance.restoreCustomField(uuid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20027);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
