/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeloApi.ProjectsApi();
  });

  describe('(package)', function() {
    describe('ProjectsApi', function() {
      describe('activateProject', function() {
        it('should call activateProject successfully', function(done) {
          // TODO: uncomment, update parameter values for activateProject call and complete the assertions
          /*

          instance.activateProject(projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('archiveProject', function() {
        it('should call archiveProject successfully', function(done) {
          // TODO: uncomment, update parameter values for archiveProject call and complete the assertions
          /*

          instance.archiveProject(projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createProject', function() {
        it('should call createProject successfully', function(done) {
          // TODO: uncomment, update parameter values for createProject call and complete the assertions
          /*

          instance.createProject(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.ProjectBasic);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createProjectFromTemplate', function() {
        it('should call createProjectFromTemplate successfully', function(done) {
          // TODO: uncomment, update parameter values for createProjectFromTemplate call and complete the assertions
          /*

          instance.createProjectFromTemplate(body, templateId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2005);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteProject', function() {
        it('should call deleteProject successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteProject call and complete the assertions
          /*

          instance.deleteProject(projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllProjects', function() {
        it('should call getAllProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllProjects call and complete the assertions
          /*
          var opts = {};

          instance.getAllProjects(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getArchivedProjects', function() {
        it('should call getArchivedProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getArchivedProjects call and complete the assertions
          /*
          var opts = {};

          instance.getArchivedProjects(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getInvitedProjects', function() {
        it('should call getInvitedProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getInvitedProjects call and complete the assertions
          /*
          var opts = {};

          instance.getInvitedProjects(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProject', function() {
        it('should call getProject successfully', function(done) {
          // TODO: uncomment, update parameter values for getProject call and complete the assertions
          /*

          instance.getProject(projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.ProjectDetail);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProjectWorkers', function() {
        it('should call getProjectWorkers successfully', function(done) {
          // TODO: uncomment, update parameter values for getProjectWorkers call and complete the assertions
          /*
          var opts = {};

          instance.getProjectWorkers(projectId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProjects', function() {
        it('should call getProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getProjects call and complete the assertions
          /*
          var opts = {};

          instance.getProjects(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FreeloApi.ProjectWithTasklists);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTemplateProjects', function() {
        it('should call getTemplateProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getTemplateProjects call and complete the assertions
          /*
          var opts = {};

          instance.getTemplateProjects(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUserProjects', function() {
        it('should call getUserProjects successfully', function(done) {
          // TODO: uncomment, update parameter values for getUserProjects call and complete the assertions
          /*
          var opts = {};

          instance.getUserProjects(userId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeProjectWorkersByEmails', function() {
        it('should call removeProjectWorkersByEmails successfully', function(done) {
          // TODO: uncomment, update parameter values for removeProjectWorkersByEmails call and complete the assertions
          /*

          instance.removeProjectWorkersByEmails(body, projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeProjectWorkersByIds', function() {
        it('should call removeProjectWorkersByIds successfully', function(done) {
          // TODO: uncomment, update parameter values for removeProjectWorkersByIds call and complete the assertions
          /*

          instance.removeProjectWorkersByIds(body, projectId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
