/*
 * Freelo API
 * API documentation for [Freelo.io](https://www.freelo.io) - Project Management Tool.  ## Request Format All requests point to URL that begins with `https://api.freelo.io/v1/`. Each request must include a `User-Agent` HTTP header.  ### Example: Projects List ```bash curl -u your@email.tld:API_KEY -H 'User-Agent: Your_App_Id (email@company.tld)' \\     https://api.freelo.io/v1/projects ```  ## Response Format The API only supports JSON format in UTF-8 encoding.  ## Authentication Authentication is done using HTTP Basic Authentication. Use your email as username and API key as password. You can find the API key in [settings](https://app.freelo.io/profil/nastaveni).  ## Rate Limiting You can perform up to 25 requests per minute. If you exceed this limit, 429 Too Many Requests HTTP status code will be returned. You have to wait at least 60 seconds before sending another request.  ## Currencies Format All currency amounts must be strings with exactly 2 decimal places multiplied by 100.  Supported currencies: CZK, EUR, USD  Examples: - `1,000.25` = `\"100025\"` - `1,000` = `\"100000\"` - `1` = `\"100\"`  ## Pagination Pages are set via GET parameter `p` starting from 0.  ## Ordering Use `order_by` and `order` (asc/desc) parameters where supported. 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.75
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FreeloApi);
  }
}(this, function(expect, FreeloApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FreeloApi.TasksApi();
  });

  describe('(package)', function() {
    describe('TasksApi', function() {
      describe('activateTask', function() {
        it('should call activateTask successfully', function(done) {
          // TODO: uncomment, update parameter values for activateTask call and complete the assertions
          /*

          instance.activateTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTask', function() {
        it('should call createTask successfully', function(done) {
          // TODO: uncomment, update parameter values for createTask call and complete the assertions
          /*

          instance.createTask(body, projectId, tasklistId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.TaskCreated);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTaskFromTemplate', function() {
        it('should call createTaskFromTemplate successfully', function(done) {
          // TODO: uncomment, update parameter values for createTaskFromTemplate call and complete the assertions
          /*

          instance.createTaskFromTemplate(body, templateId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20013);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTaskReminder', function() {
        it('should call createTaskReminder successfully', function(done) {
          // TODO: uncomment, update parameter values for createTaskReminder call and complete the assertions
          /*

          instance.createTaskReminder(body, taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20011);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletePublicLinkToTask', function() {
        it('should call deletePublicLinkToTask successfully', function(done) {
          // TODO: uncomment, update parameter values for deletePublicLinkToTask call and complete the assertions
          /*

          instance.deletePublicLinkToTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTask', function() {
        it('should call deleteTask successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTask call and complete the assertions
          /*

          instance.deleteTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTaskReminder', function() {
        it('should call deleteTaskReminder successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTaskReminder call and complete the assertions
          /*

          instance.deleteTaskReminder(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTotalTimeEstimate', function() {
        it('should call deleteTotalTimeEstimate successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTotalTimeEstimate call and complete the assertions
          /*

          instance.deleteTotalTimeEstimate(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteUserTimeEstimate', function() {
        it('should call deleteUserTimeEstimate successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteUserTimeEstimate call and complete the assertions
          /*

          instance.deleteUserTimeEstimate(taskId, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editTask', function() {
        it('should call editTask successfully', function(done) {
          // TODO: uncomment, update parameter values for editTask call and complete the assertions
          /*

          instance.editTask(body, taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.TaskDetail);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editTaskDescription', function() {
        it('should call editTaskDescription successfully', function(done) {
          // TODO: uncomment, update parameter values for editTaskDescription call and complete the assertions
          /*

          instance.editTaskDescription(body, taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.Comment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('finishTask', function() {
        it('should call finishTask successfully', function(done) {
          // TODO: uncomment, update parameter values for finishTask call and complete the assertions
          /*

          instance.finishTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllTasks', function() {
        it('should call getAllTasks successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllTasks call and complete the assertions
          /*
          var opts = {};

          instance.getAllTasks(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getFinishedTasks', function() {
        it('should call getFinishedTasks successfully', function(done) {
          // TODO: uncomment, update parameter values for getFinishedTasks call and complete the assertions
          /*
          var opts = {};

          instance.getFinishedTasks(tasklistId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20010);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPublicLinkToTask', function() {
        it('should call getPublicLinkToTask successfully', function(done) {
          // TODO: uncomment, update parameter values for getPublicLinkToTask call and complete the assertions
          /*

          instance.getPublicLinkToTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.InlineResponse20012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTask', function() {
        it('should call getTask successfully', function(done) {
          // TODO: uncomment, update parameter values for getTask call and complete the assertions
          /*

          instance.getTask(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.TaskDetail);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTaskDescription', function() {
        it('should call getTaskDescription successfully', function(done) {
          // TODO: uncomment, update parameter values for getTaskDescription call and complete the assertions
          /*

          instance.getTaskDescription(taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.Comment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTasksInTasklist', function() {
        it('should call getTasksInTasklist successfully', function(done) {
          // TODO: uncomment, update parameter values for getTasksInTasklist call and complete the assertions
          /*
          var opts = {};

          instance.getTasksInTasklist(projectId, tasklistId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FreeloApi.TaskSummary);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('moveTask', function() {
        it('should call moveTask successfully', function(done) {
          // TODO: uncomment, update parameter values for moveTask call and complete the assertions
          /*
          var opts = {};

          instance.moveTask(taskId, tasklistId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setTotalTimeEstimate', function() {
        it('should call setTotalTimeEstimate successfully', function(done) {
          // TODO: uncomment, update parameter values for setTotalTimeEstimate call and complete the assertions
          /*

          instance.setTotalTimeEstimate(body, taskId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('setUserTimeEstimate', function() {
        it('should call setUserTimeEstimate successfully', function(done) {
          // TODO: uncomment, update parameter values for setUserTimeEstimate call and complete the assertions
          /*

          instance.setUserTimeEstimate(body, taskId, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FreeloApi.SuccessResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
